In [1]:
import numpy as np
import math

                mean = Sum of all elements / Total number of elements

In [2]:
def promedio(array):
    print(type(array))
    sumatoria = 0
    
    for i in array:
        sumatoria += i
        
    return sumatoria/len(array)

In [3]:
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(promedio(a))

<class 'numpy.ndarray'>
4.5


In [5]:
r = np.random.randint(0,15, size=(1,10))
print(r[0])

[ 3  6 13 10 10  4 13 14  1 12]


In [6]:
print(promedio(r[0]))

<class 'numpy.ndarray'>
8.6


               Median = Calculated after organizing the elements in the array
                For an odd number of elements, it is the element in the middle
       For an even number of elements, it is the mean of the two elements in the middle

In [7]:
def mediana(array):
    a = len(array)/2
        
    if a%2 != 1:
        b = np.sort(array)
        print(b)
        print('The array has an odd number of elements. The median is:')
        a = int(a)
        return b[a]
    
    if a%2 == 1:
        b = np.sort(array)
        print(b)
        print('The array has an even number of elements. The median is:')
        a = int(a)
        c = b[0:a]
        d = b[a:]
        print((c[-1]+d[0])/2)


In [8]:
array2 = np.arange(0,10)
print(array2)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
mediana(array2)

[0 1 2 3 4 5 6 7 8 9]
The array has an even number of elements. The median is:
4.5


In [10]:
array3 = np.arange(0,11)
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
mediana(array3)

[ 0  1  2  3  4  5  6  7  8  9 10]
The array has an odd number of elements. The median is:


5

In [12]:
r = np.random.randint(0,15, size=(1,11))
print(r[0])

[ 2  1 13  3 14  2  1  1  1  5 14]


In [13]:
print(mediana(r[0]))

[ 1  1  1  1  2  2  3  5 13 14 14]
The array has an odd number of elements. The median is:
2


In [14]:
r = np.random.randint(0,15, size=(1,12))
print(r[0])

[ 5  5  3  1  4 12  3  5  0  5  0  1]


In [15]:
print(mediana(r[0]))

[ 0  0  1  1  3  3  4  5  5  5  5 12]
The array has an odd number of elements. The median is:
4


                    var = (Sum (element - mean)^2 ) / (n)

In [16]:
def varianza(array):
    print(type(array))
    counter = 0
    array1 = []
    
    for i in array:
        counter += i
        a1 = float(counter/len(array))
        
    for i in array:
        a2 = (i - a1)**2
        array1.append(a2)
        a3 = sum(array1)
        a4 = a3/(len(array)-1)
    
    return (a4)


In [17]:
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
varianza(array)

<class 'numpy.ndarray'>


9.166666666666666

In [19]:
r = np.random.randint(0,15, size=(1,13))
print(r[0])

[ 8  7 13  8 14  4  6  5  0  1  4 14 10]


In [20]:
print(varianza(r[0]))

<class 'numpy.ndarray'>
21.025641025641022


                stDev = Sqrt ((Sum (element - mean)^2 ) / (n-1))

In [21]:
def desviacionStandard(array):
    print(type(array))
    counter = 0
    array1 = []
    
    for i in array:
        counter += i
        a1 = float(counter/len(array))
        
    for i in array:
        a2 = (i - a1)**2
        array1.append(a2)
        a3 = sum(array1)
        a4 = a3/(len(array)-1)

    return math.sqrt(a4)


In [22]:
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
desviacionStandard(array)

<class 'numpy.ndarray'>


3.0276503540974917

In [24]:
r = np.random.randint(0,15, size = (1,13))
print(r[0])

[12  8 12  9  2  9 14 10 10  7  3  5 12]


In [25]:
print(desviacionStandard(r[0]))

<class 'numpy.ndarray'>
3.6374124361651963


                                   Standard Error of the Mean = SEM = stDev/sqRt(n)

In [26]:
def SEM(array):
    print(type(array))
    counter = 0
    array1 = []
    
    for i in array:
        counter += i
        a1 = float(counter/len(array))
        
    for i in array:
        a2 = (i - a1)**2
        array1.append(a2)
        a3 = sum(array1)
        a4 = a3/(len(array)-1)
        a5 = math.sqrt(a4)
        
    return a5/math.sqrt(len(array))


In [27]:
r = np.random.randint(0,15, size = (1,13))
print(r[0])


[10  5  2  6 14 12  5 13 13  1  5  9  8]


In [28]:
print(SEM(r[0]))

<class 'numpy.ndarray'>
1.1954054052246195


In [29]:
# The previous formula for SEM works on a single array, but the SEM has no sense when calculated on a single set.

In [30]:
"""Para calcular el SEM se deben tener varias muestras de la poblacion.
Para esto, primero voy a generar una poblacion de datos y de alli tomare 5 muestras.
Entre mas grande es el tamaño muestral mas pequeño sera el SEM (nivel de incertidumbre).
En otras palabras entre mas muestras se toman mejor se puede conocer la media poblacional."""

'Para calcular el SEM se deben tener varias muestras de la poblacion.\nPara esto, primero voy a generar una poblacion de datos y de alli tomare 5 muestras.\nEntre mas grande es el tamaño muestral mas pequeño sera el SEM (nivel de incertidumbre).\nEn otras palabras entre mas muestras se toman mejor se puede conocer la media poblacional.'

In [51]:
# Generate an array of size 13, made of random numbers that go from 1 to 15.
# This is, for example, the population data.

test = np.random.choice(15, 13)
print(test)

[ 1  2  1  4  0 11  7 13  7 10  1  6  4]


In [52]:
# Generate a uniform random sample from the array called test, of size 5:
s1 = np.random.choice(test, 5)
print(s1)

[1 2 7 1 1]


In [53]:
# Generate a uniform random sample from the array called test, of size 5:
s2 = np.random.choice(test, 5)
print(s2)

[10  1  1  2  1]


In [54]:
# Generate a uniform random sample from the array called test, of size 5:
s3 = np.random.choice(test, 5)
print(s3)

[10  1  0 10  0]


In [55]:
# Generate a uniform random sample from the array called test, of size 5:
s4 = np.random.choice(test, 5)
print(s4)

[7 4 1 1 0]


In [56]:
# Generate a non-uniform random sample from the array called test, of size 5.
# The probability to withdraw each element from the array is given by the parameter p.
# The total number of probabilities should add up to 1
s5 = np.random.choice(test, 5, p=[0.2,0.1,0.15,0.1,0.1,0.15,0,0.05,0.05,0,0,0.05,0.05])
print(s5)

[ 1  1  1 13 11]


In [64]:
print(test)
print(s1,'\n',s2,'\n',s3,'\n',s4,'\n',s5)
print(type(s1))

[ 1  2  1  4  0 11  7 13  7 10  1  6  4]
[1 2 7 1 1] 
 [10  1  1  2  1] 
 [10  1  0 10  0] 
 [7 4 1 1 0] 
 [ 1  1  1 13 11]
<class 'numpy.ndarray'>


In [57]:
samples = np.concatenate(([s1],[s2],[s3],[s4],[s5]))
print(samples)

[[ 1  2  7  1  1]
 [10  1  1  2  1]
 [10  1  0 10  0]
 [ 7  4  1  1  0]
 [ 1  1  1 13 11]]


In [58]:
# Now make a function to generate uniform random samples from a single "population" set.

In [59]:
def randomSamples(array):
    samples = []
    for i in array[1:]:
        sample = np.random.choice(array, 5)
        if len(samples) == 0:
            samples = [sample]
        else:
            samples = np.append(samples, [sample], axis=0)
    return samples


In [60]:
test1 = np.random.choice(15, 13)
sampling3 = randomSamples(test1)
print(sampling3)
print(type(sampling3))

[[13 13 13  7 13]
 [ 3 11  7 13  7]
 [ 5 11 13  3  1]
 [ 7  3  6 13  5]
 [13 11 13  3  7]
 [11 13 13  3  1]
 [ 7 13 14  6 11]
 [ 7  7 14  7 13]
 [11  1  7  7  7]
 [ 3  7  7  5 13]
 [ 5  5 13 14  7]
 [ 6  7 11  6 14]]
<class 'numpy.ndarray'>


In [61]:
sampling3.shape

(12, 5)

In [62]:
# Now, improve the SEM function such that it works with an array of arrays. Esto va en proceso.

In [63]:
def SEM1(array):
    counter = 0
    array1 = []
    i = 0
    
    array1 = array
    a,b,c,d,e,f,g,h,j,k,l,m,n = map(list, zip(*array1))
    print(a)
    
    for i in array:
        i += 1
        arrays = np.split(array, 12)
        print(arrays)
        
        for array in arrays:
            counter += i
            a1 = float(counter/len(array))

        for i in a[i]:
            a2 = (i - a1)**2
            array1.append(a2)
            a3 = sum(array1)
            a4 = a3/(len(array)-1)
            a5 = math.sqrt(a4)

        return a5/math.sqrt(len(array))

In [66]:
print(SEM(sampling3))

<class 'numpy.ndarray'>


TypeError: only size-1 arrays can be converted to Python scalars