In [3]:
import pandas as pd
import numpy as np
import pylab as pl
import seaborn as sns; sns.set()
from sklearn import preprocessing
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
%matplotlib inline


In [4]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
cols = ["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]
x = df[cols]
y = df.Outcome

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=0)

In [7]:
lr = LogisticRegression(solver='lbfgs', max_iter=200)
lr.fit(x_train, y_train)
y_pre = lr.predict(x_test)

In [8]:
y_pre

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])

In [9]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
661            1      199             76             43        0  42.9   
122            2      107             74             30      100  33.6   
113            4       76             62              0        0  34.0   
14             5      166             72             19      175  25.8   
529            0      111             65              0        0  24.6   
..           ...      ...            ...            ...      ...   ...   
366            6      124             72              0        0  27.6   
301            2      144             58             33      135  31.6   
382            1      109             60              8      182  25.4   
140            3      128             78              0        0  21.1   
463            5       88             78             30        0  27.6   

     DiabetesPedigreeFunction  Age  
661                     1.394   22  
122                     0.404   23  
113                     0.391   25  
14                      0.587   51  
529                     0.660   31  
..                        ...  ...  
366                     0.368   29  
301                     0.422   25  
382                     0.947   21  
140                     0.268   55  
463                     0.258   37  

[192 rows x 8 columns]

In [10]:
metrics.accuracy_score(y_test, y_pre)

0.8020833333333334

In [12]:
person1a2 = x.iloc[0:4]
person1a2.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21

In [11]:
lr.predict(person1a2)

array([1, 0, 1, 0])

In [12]:
person1a2['BloodPressure'] = person1a2['BloodPressure'] + 1
person1a2

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             73             35        0  33.6   
1            1       85             67             29        0  26.6   
2            8      183             65              0        0  23.3   
3            1       89             67             23       94  28.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21

In [13]:
lr.predict(person1a2)

array([1, 0, 1, 0])

In [ ]:
person1a2['Insulin'] = person1a2['Insulin'] + 50
person1a2

In [ ]:
lr.predict(person1a2)

In [ ]:
person1a2['DiabetesPedigreeFunction'] = person1a2['DiabetesPedigreeFunction'] + .25
person1a2

In [ ]:
lr.predict(person1a2)

In [ ]:
person1a2['Pregnancies'] = person1a2['Pregnancies'] + 5
person1a2

In [ ]:
lr.predict(person1a2)

In [ ]:
person1a2.iloc[0::2,1]

In [ ]:
person1a2['Glucose'] = person1a2['Glucose'] + 60
person1a2

In [ ]:
lr.predict(person1a2)

In [9]:
a = x_test.iloc[182:]
a

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
490            2       83             65             28       66  36.8   
45             0      180             66             39        0  42.0   
750            4      136             70              0        0  31.2   
62             5       44             62              0        0  25.0   
78             0      131              0              0        0  43.2   
366            6      124             72              0        0  27.6   
301            2      144             58             33      135  31.6   
382            1      109             60              8      182  25.4   
140            3      128             78              0        0  21.1   
463            5       88             78             30        0  27.6   

     DiabetesPedigreeFunction  Age  
490                     0.629   24  
45                      1.893   25  
750                     1.182   22  
62                      0.587   36  
78                      0.270   26  
366                     0.368   29  
301                     0.422   25  
382                     0.947   21  
140                     0.268   55  
463                     0.258   37

In [10]:
lr.predict(a)

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [11]:
a['Pregnancies'] = a['Pregnancies'] + 4  
a

C:\Users\TheGlitchCat\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
490            6       83             65             28       66  36.8   
45             4      180             66             39        0  42.0   
750            8      136             70              0        0  31.2   
62             9       44             62              0        0  25.0   
78             4      131              0              0        0  43.2   
366           10      124             72              0        0  27.6   
301            6      144             58             33      135  31.6   
382            5      109             60              8      182  25.4   
140            7      128             78              0        0  21.1   
463            9       88             78             30        0  27.6   

     DiabetesPedigreeFunction  Age  
490                     0.629   24  
45                      1.893   25  
750                     1.182   22  
62                      0.587   36  
78                      0.270   26  
366                     0.368   29  
301                     0.422   25  
382                     0.947   21  
140                     0.268   55  
463                     0.258   37

In [12]:
a['Glucose'] = a['Glucose'] + 40
a

C:\Users\TheGlitchCat\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
490            6      123             65             28       66  36.8   
45             4      220             66             39        0  42.0   
750            8      176             70              0        0  31.2   
62             9       84             62              0        0  25.0   
78             4      171              0              0        0  43.2   
366           10      164             72              0        0  27.6   
301            6      184             58             33      135  31.6   
382            5      149             60              8      182  25.4   
140            7      168             78              0        0  21.1   
463            9      128             78             30        0  27.6   

     DiabetesPedigreeFunction  Age  
490                     0.629   24  
45                      1.893   25  
750                     1.182   22  
62                      0.587   36  
78                      0.270   26  
366                     0.368   29  
301                     0.422   25  
382                     0.947   21  
140                     0.268   55  
463                     0.258   37

In [13]:
a['DiabetesPedigreeFunction'] = a['DiabetesPedigreeFunction'] - .050
a

C:\Users\TheGlitchCat\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
490            6      123             65             28       66  36.8   
45             4      220             66             39        0  42.0   
750            8      176             70              0        0  31.2   
62             9       84             62              0        0  25.0   
78             4      171              0              0        0  43.2   
366           10      164             72              0        0  27.6   
301            6      184             58             33      135  31.6   
382            5      149             60              8      182  25.4   
140            7      168             78              0        0  21.1   
463            9      128             78             30        0  27.6   

     DiabetesPedigreeFunction  Age  
490                     0.579   24  
45                      1.843   25  
750                     1.132   22  
62                      0.537   36  
78                      0.220   26  
366                     0.318   29  
301                     0.372   25  
382                     0.897   21  
140                     0.218   55  
463                     0.208   37

In [14]:
a['Age'] = a['Age'] - 8
a

C:\Users\TheGlitchCat\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
490            6      123             65             28       66  36.8   
45             4      220             66             39        0  42.0   
750            8      176             70              0        0  31.2   
62             9       84             62              0        0  25.0   
78             4      171              0              0        0  43.2   
366           10      164             72              0        0  27.6   
301            6      184             58             33      135  31.6   
382            5      149             60              8      182  25.4   
140            7      168             78              0        0  21.1   
463            9      128             78             30        0  27.6   

     DiabetesPedigreeFunction  Age  
490                     0.579   16  
45                      1.843   17  
750                     1.132   14  
62                      0.537   28  
78                      0.220   18  
366                     0.318   21  
301                     0.372   17  
382                     0.897   13  
140                     0.218   47  
463                     0.208   29

In [24]:
lr.predict(a)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [16]:
a.shape

(10, 8)