In [2]:
import numpy as np

In [3]:
print("Welcome to Battleship")
print("This is a two player game")
print("Each player will have two boards, a fleet board and an enemy log board")

Welcome to Battleship
This is a two player game
Each player will have two boards, a fleet board and an enemy log board


In [4]:
print("Player 1, please make your 2 game boards of size 7*7 each one")
print()
print("player1, fleet board is p1_fb:")
print()
p1_fb= np.zeros((7,7))
print(p1_fb)
print()
print("player1, enemy log board is p1_eb:")
p1_eb = np.zeros((7,7))
print(p1_eb)

Player 1, please make your 2 game boards of size 7*7 each one

player1, fleet board is p1_fb:

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

player1, enemy log board is p1_eb:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [5]:
print("Player 1, fleet positioning")
print()
print("Your fleet is made of 1 size-4 boat, 2 size-3 boats, and 3 size-2 boats")
print("Please, position your fleet on the board:")
print()
boats=[1,2,3,4,5,6,]
for i in boats:
    i=input("Position the boat by choosing the coordinates x1:x2,y1:y2 on the p1_fb ")
    x,y = i.split(",")
    x1,x2 = x.split(":")
    y1,y2 = y.split(":")
    x1,x2,y1,y2 = int(x1),int(x2),int(y1),int(y2)
    p1_fb[x1:x2,y1:y2]= 1
print()
print("This is the player 1 fleet board (p1_fb): ")
print(p1_fb)
#    1:5,1:2       3:6,5:6      0:1,3:6       5:6,3:5       1:2,4:6       4:5,2:4

Player 1, fleet positioning

Your fleet is made of 1 size-4 boat, 2 size-3 boats, and 3 size-2 boats
Please, position your fleet on the board:

Position the boat by choosing the coordinates x1:x2,y1:y2 on the p1_fb 1:5,1:2 
Position the boat by choosing the coordinates x1:x2,y1:y2 on the p1_fb 3:6,5:6
Position the boat by choosing the coordinates x1:x2,y1:y2 on the p1_fb 0:1,3:6
Position the boat by choosing the coordinates x1:x2,y1:y2 on the p1_fb 5:6,3:5
Position the boat by choosing the coordinates x1:x2,y1:y2 on the p1_fb 1:2,4:6
Position the boat by choosing the coordinates x1:x2,y1:y2 on the p1_fb 4:5,2:4

This is the player 1 fleet board (p1_fb): 
[[0. 0. 0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
print("Player 2, please make your 2 game boards of size 7*7 each one")
print("player2, fleet board is p2_fb:")
p2_fb= np.zeros((7,7))
print(p2_fb)
print()
print("player2, enemy log board is p2_eb:")
p2_eb = np.zeros((7,7))
print(p2_eb)

Player 2, please make your 2 game boards of size 7*7 each one
player2, fleet board is p2_fb:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

player2, enemy log board is p2_eb:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
print("Player2, fleet positioning")
print()
print("Your fleet is made of 1 size-4 boat, 2 size-3 boats, and 3 size-2 boats")
print("Please, position your fleet on the board:")
print()
boats=[1,2,3,4,5,6,]
for i in boats:
    i=input("Position the boat by choosing a coordinate x1:x2,y1:y2 on the board p2_fb: ")
    x,y = i.split(",")
    x1,x2 = x.split(":")
    y1,y2 = y.split(":")
    x1,x2,y1,y2 = int(x1),int(x2),int(y1),int(y2)
    p2_fb[x1:x2,y1:y2]= 1
print()
print("This is the player 2 fleet board (p2_fb): ")
print(p2_fb)

#      0:4,0:1      5:6,0:2       3:4,2:5        2:3,3:6      0:1,2:4       0:1,4:6

Player2, fleet positioning

Your fleet is made of 1 size-4 boat, 2 size-3 boats, and 3 size-2 boats
Please, position your fleet on the board:

Position the boat by choosing a coordinate x1:x2,y1:y2 on the board p2_fb: 0:4,0:1
Position the boat by choosing a coordinate x1:x2,y1:y2 on the board p2_fb: 5:6,0:2
Position the boat by choosing a coordinate x1:x2,y1:y2 on the board p2_fb: 3:4,2:5
Position the boat by choosing a coordinate x1:x2,y1:y2 on the board p2_fb: 2:3,3:6
Position the boat by choosing a coordinate x1:x2,y1:y2 on the board p2_fb: 0:1,2:4
Position the boat by choosing a coordinate x1:x2,y1:y2 on the board p2_fb: 0:1,4:6

This is the player 2 fleet board (p2_fb): 
[[1. 0. 1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [8]:
"""The fleet positions of player 1 and player 2"""
print(p1_fb)
print()
print(p2_fb)

[[0. 0. 0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[[1. 0. 1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [9]:
i = p1_fb.sum()
j = p2_fb.sum()
print(i,j)

16.0 16.0


In [10]:
while i or j != 0:
    Turn = input("Who's turn is this? player 1 or 2 :")
    player = Turn

    if player == '1': # It is skipping this if and it goes directly to else, not recognizing "player"
        player1 = input("player1, choose a coordinate x,y on the board p2_fb: ")
        x,y = player1.split(",")
        x,y = int(x),int(y)
        p2_fb[x,y] = 0
        print(j)
        if j < 16:
            print("You hit a boat")
            j-=1     
        print(p2_fb)
    
    if player == '2':
        player2 = input("player2, choose a coordinate x,y on the board p1_fb: ")
        x,y = player2.split(",")
        x,y = int(x),int(y)
        p1_fb[x,y] = 0 # If there is a 1 in player 2 fleet board, the boat would start to sink
        j = p1_fb.sum()
        print(j)
        if p1_fb.sum() < 16:
            print("You hit a boat")
            j-=1
        print(p1_fb)

Who's turn is this? player 1 or 2 :1
player1, choose a coordinate x,y on the board p2_fb: 1,1
16.0
[[1. 0. 1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


KeyboardInterrupt: 

In [11]:
comparison=(p1_fb, p2_fb)
for any in comparison:
    if all in p1_fb == np.zeros(7,7):
        print('Player 1 has won')
        break
                
    elif all in p2_fb == np.zeros(7,7):
        print("Player 2 has won")
        break
    
print("Game over")

Game over
